version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceMonitoringPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceMonitoringPlugin.Integration.Test"
  schedule:
    interval: daily